### ISSUE TITLE
convert to onnx error

### ISSUE THREAD

**Issue by ForestWang** [chenjun2hao/CenterFace.pytorch#11]
Hi Sir:
    when converting to onnx, got the error:
   "RuntimeError: Only tuples, lists and Variables supported as JIT inputs, but got dict"
   could you figure it out?

many thanks.

**Comment by chenjun2hao** [comment]
you should uncommit this line `# @dict2list         # 转onnx的时候需要将输出由dict转成list模式` in [centerface_mobilenet_v2_fpn.py](https://github.com/chenjun2hao/CenterFace.pytorch/blob/master/src/lib/models/Backbone/centerface_mobilenet_v2_fpn.py)
