### ISSUE TITLE
为什么requirements里面安装的东西这么多？

### ISSUE THREAD

**Issue by immarioo** [chenjun2hao/CenterFace.pytorch#16]
paddlepaddle，tensorflow，pytorch都安装了，程序中有用到所有的框架吗？

**Comment by chenjun2hao** [comment]
只用了pytorch，我的conda环境中安装了那些。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "mario"<notifications@github.com&gt;; 
发送时间: 2020年4月15日(星期三) 下午4:11
收件人: "chenjun2hao/CenterFace.pytorch"<CenterFace.pytorch@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [chenjun2hao/CenterFace.pytorch] 为什么requirements里面安装的东西这么多？ (#16)





 
paddlepaddle，tensorflow，pytorch都安装了，程序中有用到所有的框架吗？

**Comment by immarioo** [comment]
感谢回答，我下载好model_best.pth后执行python test_wider_face.py，但是出来的结果没有landmark点，得分阈值也没找到哪里设置，在opts_pose.py中line196修改了scores_thresh，由原始的0.1修改为0.4后检测结果还是一样，是不是找的地方不对？另外执行训练的main.py位置是不是没放正确啊，应该是在src下。
第一幅是我检测的结果，第二幅是文件夹中的结果。
![000388_res](https://user-images.githubusercontent.com/12837585/79411537-a61e8100-7fd5-11ea-8cd4-af8d9463934c.jpg)
![000388_result](https://user-images.githubusercontent.com/12837585/79411782-496f9600-7fd6-11ea-92c6-14a92a2ab02d.png)

**Comment by chenjun2hao** [comment]
我测试一下，回复
