### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by JiHaoqina** [chenjun2hao/CenterFace.pytorch#23]
Hi, you say achieve the better result than the original acc in this repo,
( yours: 0.9206 | 0.9089 | 0.7846   papers: 0.922 | 0.911 | 0.782 )
but I found that you use a IoU thr=0.4 when you compute the final mAP, which is wrong because original matlab eval tool use a IoU thr=0.5, and that's the reason why you got the above performance.
So I don't think it's a fair comparison. Can you explain this? Thx.

**Comment by chenjun2hao** [comment]
the original paper also use IOU threshold = 0.4, not 0.5.
