### ISSUE TITLE
请问在目前版本再简化的话有什么思路么

### ISSUE THREAD

**Issue by DuckJ** [chenjun2hao/CenterFace.pytorch#5]
我准备试试如果在训练随机crop正方形然后resize成300之后，测试时候的尺度也按照长宽比长边resize到300附近，这样看看 性能下降多少

**Comment by chenjun2hao** [comment]
推理的话，可以参考[face_mask](https://github.com/chenjun2hao/facemask)，只回归了人脸bbox部分，没有landmarks。训练采用的512×512的尺寸。小尺寸图片训练对精度还是有很大影响的。
