### ISSUE TITLE
About the model structure?

### ISSUE THREAD

**Issue by SyGoing** [chenjun2hao/CenterFace.pytorch#7]
1、Your mobilenetv2 is original structure whose activation is relu6 , And the original centerface is relu. Have try the relu version?  
2、Also your custom centerface is trained with the five landmarks? or you just trained the bbox with no landmarks?

original centerface's landmarks are trained by the offset regression not heat map and its' size added the log regression .

**Comment by chenjun2hao** [comment]
1. i don't try the relu;
2. i train the model with the five landmarks.

**Comment by SyGoing** [comment]
Thanks for your reply , I will also train the centerface and upload it to github

**Comment by SyGoing** [comment]
I have trained these model with only bbox ,but the model is not good enough

**Comment by chenjun2hao** [comment]
@SyGoing I have update the readme for train tricks.

**Comment by chenjun2hao** [comment]
@SyGoing I have update the readme for train tricks.
