### ISSUE TITLE
coco format annotation file

### ISSUE THREAD

**Issue by zhangming8** [chenjun2hao/CenterFace.pytorch#8]
The link of COCO format annotation file has be removed by Baidu cloud?
Can you provide it again?

**Comment by chenjun2hao** [comment]
have updated

**Comment by YangYangGirl** [comment]
![image](https://user-images.githubusercontent.com/32426369/97959220-d0a51f80-1de9-11eb-8058-09c2486ff140.png)

感谢您的工作，上图是你提供的链接中的验证集，其中标签是空的。但是，你在保存 mobel_best.pth时，仍然使用的是val
_loader，导致模型的model_best.pth始终为第一个保存的模型。[https://github.com/chenjun2hao/CenterFace.pytorch/blob/37a351be07606136561bc56eae716f8575b61e00/src/main.py#L91](url)
